@extends('layouts.contractor')
@section('content')
<div class="card shadow-lg">
    <div class="card-header bg-primary text-white">
        <h5 class="m-0">Surveys Data</h5>
    </div>
        <div class="card-body">
            @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ session('status') }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            <!-- Survey Table -->
            <div class="table-responsive">
                <table class="table table-bordered table-striped" id="table-survey" width="100%" cellspacing="0">
                    <thead class="thead-light">
                        <tr>
                            <th>#</th>
                            <th>Nama</th>
                            <th>Pemilik</th>
                            <th>Maps</th>
                            <th>Kontak</th>
                            <th>Keterangan</th>
                            <th>Tgl Prospect</th>
                            <th>Survey</th>
                            <th>Tgl Survey</th>
                            <th>Gambar</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Dynamic rows go here, generated by JavaScript or Blade -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    @include('contractor.survey.script')
@endpush
